name: yicore
description: Yicore是为 YiClass 课表项目打造的轻量级 Flutter 组件库

version: 1.0.6

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any

flutter:
  uses-material-design: true

